
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: psql
spec:
  ports:
    - port: 5432
  selector:
    app: psql
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: psql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: psql
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: psql
      tier: postgreSQL
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: psql
        tier: postgreSQL
    spec:
      containers:
        - image: postgres
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres

            - name: PSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  db_name

            - name: PSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : psql-secrets
                  key :  password
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
