
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: kubern
spec:
  ports:
    - port: 5432
  selector:
    app: kubern
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: kubern
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: kubern
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: kubern
      tier: postgreSQL
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubern
        tier: postgreSQL
    spec:
      containers:
        - image: postgres
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: gitlab
            - name: POSTGRES_DB
              value: gitlabhq_production
            - name: POSTGRES_PASSWORD
              value: gitlab
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
