server:
  port: 8080

spring:
  application:
    name: KUBERNETEC
  datasource:
    password: postgres
#      ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/orders
#    ${DB_HOST}/${DB_NAME}
    username: postgres
#    ${DB_USERNAME}
    driver: org.postgresql.Drive
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect